name: flutter_space_scutum_test
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# App version: format â†’ major.minor.patch+build
version: 1.0.0+1

environment:
  # Required Dart SDK version for the project.
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
    # Used for browser URL strategies and web integration.

  # ---------------------- Navigation ----------------------
  go_router: ^17.0.0
  # Declarative routing with URL synchronization and deep linking.

  # ---------------------- Utilities -----------------------
  intl: ^0.20.2        # Date/time formatting.
  equatable: ^2.0.7    # Value equality for domain/entities.
  uuid: ^4.5.1         # Unique ID generation.

  # ---------------------- State Management ----------------
  bloc: ^9.1.0               # Business logic components.
  bloc_concurrency: ^0.3.0   # Concurrency transformers for BLoC.
  flutter_bloc: ^9.1.1       # Flutter widgets for BLoC.

  # ---------------------- Local Storage -------------------
  hive_ce: ^2.11.3           # Lightweight NoSQL storage.
  hive_ce_flutter: ^2.3.1    # Hive initialization for Flutter.

  # ---------------------- Dependency Injection ------------
  get_it: ^8.0.3             # Service locator.
  injectable: ^2.5.0         # Code generation for DI.

  # ---------------------- Environment Variables -----------
  flutter_dotenv: ^5.1.0     # Loads .env files.

  # ---------------------- Networking ----------------------
  dio: ^5.9.0                # HTTP client.
  retrofit: ^4.9.0           # REST API generator.
  json_annotation: ^4.9.0    # JSON serialization annotations.

  # ---------------------- Images & Caching ----------------
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0            # Recommended lint rules.

  # Code generation tools:
  json_serializable: ^6.9.4        # JSON models generation.
  build_runner: ^2.4.8             # General purpose build system.
  injectable_generator: ^2.3.0     # DI code generation.
  hive_ce_generator: ^1.9.2        # Hive `TypeAdapter` generator.
  retrofit_generator: ^10.0.0      # Creates retrofit API clients.

flutter:
  uses-material-design: true

  assets:
    # Environment variables file.
    - assets/env/.env
